version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 4000
      DROPSHIPPING_AUTO: "true"
      DROPSHIPPING_PREP: "2"
      SEED: "false"
    ports:
      - "4000:4000"
    volumes:
      - backend_data:/app/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  backend_data:
